version: "3.9"
services:
  db:
    image: postgres:16.2
    environment:
      POSTGRES_DB: calendar 
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
  backend:
    build: ./backend
    command: ["flask", "run", "--host=0.0.0.0", "--port=8000"]
    ports:
      - 8000:8000
    environment:
      - FLASK_APP=app.py  # Replace with the name of your Flask app file
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://admin:admin@db:5432/calendar
    volumes:
      - ./backend:/app
  frontend:
    build: ./frontend
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    ports:
      - 5173:5173
  

